### ISSUE TITLE
Cannot launch on Raspbian

### ISSUE THREAD

**Issue by bitigchi** [bichenkk/coinmon#20]
Hello,

After installing, I get the output below on Raspbian:

```
module.js:327
    throw err;
    ^

Error: Cannot find module 'colors'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/local/lib/node_modules/coinmon/src/index.js:7:16)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

Node.js is up to date. How to get the colors module?

Thank you very much in advance.

**Comment by hpduong** [comment]
Hi, just run `sudo npm install -g colors` if you are doing global install, otherwise run `sudo npm install colors --save` in the folder if you are in development. 

Had same error and that got it to run.

**Comment by bitigchi** [comment]
This solved it! Thank you very much.

**Comment by bichenkk** [comment]
@hpduong Thanks!
