### ISSUE TITLE
Missing path?

### ISSUE THREAD

**Issue by GarlandKey** [bichenkk/coinmon#61]
Upon attempting install:

```
path.js:975
      const path = i >= 0 ? args[i] : process.cwd();
                                              ^

Error: ENOENT: no such file or directory, uv_cwd
    at Object.resolve (path.js:975:47)
    at Function.Module._resolveLookupPaths (internal/modules/cjs/loader.js:550:17)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:648:20)
    at Function.Module._load (internal/modules/cjs/loader.js:580:25)
    at Module.require (internal/modules/cjs/loader.js:711:19)
    at require (internal/modules/cjs/helpers.js:14:16)
    at Object.<anonymous> (/usr/lib/node_modules/coinmon/src/index.js:9:20)
    at Module._compile (internal/modules/cjs/loader.js:805:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:816:10)
    at Module.load (internal/modules/cjs/loader.js:672:32)
```

**Comment by GarlandKey** [comment]
I don't know js but I gather I'm missing a path or global path. I'm using zsh.

**Comment by GarlandKey** [comment]
This can be marked as closed. This is a nodejs / npm issue and the solution is to simply close your terminal emulators and open a brand new one and attempt to install again.
